name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug"]
assignees:
  - oboupo
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: ios-version
    attributes:
      label: iOS Version
      description: Which iOS version we should use to reproduce bug?
      placeholder: iOS 8.1
  - type: input
    id: device
    attributes:
      label: Device
      description: Which Apple device we should use to reproduce bug?
      placeholder: iPhone XR
